### ISSUE TITLE
TypeError: Argument 1 passed to Magefan\GuestToCustomer\Model\Order\GuestOrderManagement::isCustomerHasUnassignedGuestOrders() must be of the type string, null given

### ISSUE THREAD

**Issue by MagefanCustomer** [magefan/magento2-convert-guest-to-customer#1]
The following error message appeared on **/checkout/onepage/success/**

**System requirement**: Magento2.4.4+Php7.4+MYSQL8

An error has happened during application run. Here is exception log for details:

`[2022-06-14T08:10:54.150718+00:00] main.CRITICAL: TypeError: Argument 1 passed to Magefan\GuestToCustomer\Model\Order\GuestOrderManagement::isCustomerHasUnassignedGuestOrders() must be of the type string, null given, called in /vendor/magefan/module-convert-guest-to-customer/Block/CustomerAccount/AssignLink.php on line 68 and defined in /vendor/magefan/module-convert-guest-to-customer/Model/Order/GuestOrderManagement.php:166
Stack trace:
#0 /vendor/magefan/module-convert-guest-to-customer/Block/CustomerAccount/AssignLink.php(68): Magefan\GuestToCustomer\Model\Order\GuestOrderManagement->isCustomerHasUnassignedGuestOrders(NULL)
#1 /var/view_preprocessed/pub/static/vendor/magefan/module-convert-guest-to-customer/view/frontend/templates/assign_link.phtml(1): Magefan\GuestToCustomer\Block\CustomerAccount\AssignLink->isCustomerHasUnassignedGuestOrders()
#2 /vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/home/wwwroot/l...')
#3 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Magefan\GuestToCustomer\Block\CustomerAccount\AssignLink\Interceptor), '/home/wwwroot/l...', Array)
#4 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array)
#5 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Magefan\GuestToCustomer\Block\CustomerAccount\AssignLink\Interceptor), '/home/wwwroot/l...', Array)
#6 /generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins('render', Array, Array)
#7 /vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render(Object(Magefan\GuestToCustomer\Block\CustomerAccount\AssignLink\Interceptor), '/home/wwwroot/l...', Array)
#8 /vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView('/home/wwwroot/l...')
#9 /vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#10 /vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#11 /vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#12 /vendor/magefan/module-convert-guest-to-customer/Block/CustomerAccount/AssignLink.php(84): Magento\Framework\View\Element\AbstractBlock->toHtml()
#13 /vendor/magento/framework/View/Layout.php(578): Magefan\GuestToCustomer\Block\CustomerAccount\AssignLink->toHtml()
#14 /vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('assign_guest_or...')
#15 /vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('assign_guest_or...')
#16 /vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('assign_guest_or...', false)
#17 /vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('columns.top', false)
#18 /vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('columns.top')
#19 /vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('columns.top', false)
#20 /vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('main.content', false)
#21 /vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('main.content')
#22 /vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('main.content', false)
#23 /vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#24 /vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#25 /vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#26 /vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('root', false)
#27 /vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('root')
#28 /vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement('root')
#29 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#30 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#31 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#32 /generated/code/Magento/Framework/View/Layout/Interceptor.php(41): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#33 /vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#34 /vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#35 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#36 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#37 /vendor/amasty/module-page-speed-tools/Plugin/ProcessPageResult.php(40): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#38 /vendor/magento/framework/Interception/Interceptor.php(135): Amasty\PageSpeedTools\Plugin\ProcessPageResult->aroundRenderResult(Object(Magento\Framework\View\Result\Page\Interceptor), Object(Closure), Object(Magento\Framework\App\Response\Http\Interceptor))
#39 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#40 /generated/code/Magento/Framework/View/Result/Page/Interceptor.php(32): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#41 /vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#42 /vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#43 /pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#44 {main} [] []`

**Comment by magefan** [comment]
Thank you for your report. 
Please edit the file vendor/magefan/module-convert-guest-to-customer/Block/CustomerAccount/AssignLink.php
and change the line 68
from
`return $this->guestOrderManagement->isCustomerHasUnassignedGuestOrders($this->customerSession->getCustomer()->getEmail());
`
to
`return $this->guestOrderManagement->isCustomerHasUnassignedGuestOrders($this->customerSession->getCustomer()->getEmail() ?: '');
`

The fix is added in the latest version of the [Magento 2 Guest to Customer Extension](https://magefan.com/magento2-convert-guest-to-customer).
